CREATE DATABASE IF NOT EXISTS csc468;
USE csc468;

CREATE TABLE IF NOT EXISTS cattle (
    id INT AUTO_INCREMENT PRIMARY KEY,
    breed VARCHAR(255),
    age INT,
    color VARCHAR(255)
);

LOAD DATA INFILE '/cattle_data.csv'
INTO TABLE cattle
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;
